### ISSUE TITLE
B: KFS Group Finder setting doesn't make all filters single select ddls (#16 Repo)

### ISSUE THREAD

**Issue by carlatKFS** [KingdomFirst/RockBlocks#25]
# Expected Behavior

The "Single Select Filters" block setting description states that "When set to true, all filters will be a drop down instead of checkbox". 

# Current Behavior

The code only actually uses it to change the core Campus filter. Maybe this was stubbed out and never finished? Description is either misleading, or it needs to also change all of the group attribute filters.

**Comment by nateh777** [comment]
Unfortunately, looking into this issue showed that we did not stub out any additional work and it was intentionally only affecting the the campus filter, I have renamed the setting to better reflect what it was built to do in #31. If someone would like this feature it will have to be an enhancement request and estimated out as it will be a significant amount of work due to using core helper methods that would not support easily converting to a single select filter control.
